#
# Site settings
#
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

gems: 
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

url: https://wurstscript.github.io/
baseurl: 
blogurl: /blog
highlighter: rouge
title: &site_title WurstScript
description: &site_description Programming language and IDE that compiles to Jass which is used in WarCraft III. The first complete, all-in-one warcraft modding environment. Get starting making your own warcraft 3 maps today - cross platform and editor independant.
branding:
  icon:
    name: icon_documents_alt
  highlight: Wurst
  bold: Script
  blog: Blog
markdown: kramdown
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  parse_block_html: true
  syntax_highlighter_opts:
    disable : true
google_site_verification: googlee4f4af3121cc4c25.html

#
# Social
#

share:
  github:
    repo: wurstscript/WurstScript
    position: center

#
# Collections
#
collections:
  doc:
    output: true
    permalink: /:path.html


#
# Default values
#
defaults:
  -
    scope:
      path: ""
      type: doc
    values:
      layout: doc
